### ISSUE TITLE
FlatList focused item 

### ISSUE THREAD

**Issue by gbebri** [douglowder/TVInputDemo#3]
I'm working with a FlatList containing a large amount of items. My goal is to focus on the item with index 100 and smoothly scroll up and down the list. Currently, I'm using scrollToIndex(), but I've noticed it takes some time to manage this operation efficiently.

Here's the relevant code snippet:
```jsx
useEffect(() => {
  if (flatListRef.current) {
    flatListRef.current.scrollToIndex({ index: initialScrollIndex, animated: true });
  }
}, []);

<FlatList
  ref={flatListRef}
  data={channels}
  renderItem={renderChannelItem}
  horizontal={false}
/>
```

**Comment by douglowder** [comment]
@gbebri You probably want to participate in some of the new feature discussions happening right now in the React Native TV repo, particularly https://github.com/react-native-tvos/react-native-tvos/discussions/665 . There is ongoing work to make focus handling in lists easier and more reliable.
